remote_theme: just-the-docs/just-the-docs

# Disable the search feature
search_enabled: false

# Include custom CSS file
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Custom CSS configuration
sass:
  custom_css: _configcustomize.css
