remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

# Default title and description for the whole site
title: "A Kendra Nelson Production . . ." 
description: "Created by me!"
search_enabled: true

# Default navigation behaviour
just_the_docs:
  show_toc: true
  toc_label: "Contents"
  toc_levels: 1..3 # Adjust table of contents depth

# Navigation sidebar (optional, can be customized in individual pages)
nav_order:
  - "Home"
  - "Chapter 1"
  - "Chapter 2"
